apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: idle-pod-scaler
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-deployment
  triggers:
  - type: cpu
    metadata:
      type: "AverageValue"
      value: "100m"
