apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}

{{- if .Values.ssh.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssh-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer
{{- end }}