name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Add Helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/my-go-app:latest ./backend/app

      - name: Make setup-prometheus.sh executable
        run: chmod +x ./scripts/setup-prometheus.sh

      - name: Deploy Prometheus and Grafana
        run: ./scripts/setup-prometheus.sh

      - name: Deploy Helm chart
        run: |
          helm install my-dynamic-environment ./helm-chart -f ./helm-chart/values.yaml

      - name: Apply Resource Quotas
        run: |
          kubectl apply -f namespaces/quotas/dev-quota.yaml

      - name: Apply Horizontal Pod Autoscaler
        run: |
          kubectl apply -f autoscaling/hpa/example-hpa.yaml

      - name: Verify deployment
        run: |
          kubectl get all
          kubectl get ingress

      - name: Debug Pods
        run: |
          echo "Listing all pods:"
          kubectl get pods -A
          echo "Describing all pods in the default namespace:"
          kubectl describe pods

      - name: Debug Events
        run: |
          echo "Listing all events:"
          kubectl get events -A